"""
Evaluation metrics for XAI-Lib explanations.

This subpackage provides metrics for evaluating the quality and
faithfulness of explanations generated by XAI-Lib explainers.

Available Metrics
-----------------

- :class:`~xailib.metrics.insertiondeletion`:
  Insertion and Deletion metrics for evaluating explanation faithfulness.

Example
-------
>>> from xailib.metrics.insertiondeletion import InsertionDeletion
>>>
>>> metric = InsertionDeletion(model, image, explanation)
>>> insertion_score = metric.insertion()
>>> deletion_score = metric.deletion()
"""
